### ISSUE TITLE
TypeError: Cannot read property 'groups' of undefined

### ISSUE THREAD

**Issue by larsgw** [no-context/moo#108]
I'm getting the following error:

```
/home/larsgw/.../node_modules/moo/moo.js:311
      var groups = state.groups
                         ^

TypeError: Cannot read property 'groups' of undefined
    at Object.compileStates [as states] (/home/larsgw/.../node_modules/moo/moo.js:311:26)
    at Object.states (/home/larsgw/.../src/moo.js:13:26)
    at ...
```

I believe it has to do with this line redefining `keys`, due to hoisting. Changing that variable and references to it to for example `keysFast` seems to work.

https://github.com/no-context/moo/blob/8b5064009b1eff7e37f097a8d562c663c404c332/moo.js#L313-L316

**Comment by larsgw** [comment]
The `master` branch, it seems to work fine on `v0.4.3`. However, all the docs (mostly those on keywords) are for the master branch, so I use that one at the moment. Example code:

```js
moo.states({
  main: {
    a: 'a',
    b: 'b'
  }
})
```
